#pragma once

#define FONT_JETBRAINS "fonts/JetBrainsMono-Regular.ttf"

#define TILE_LEVEL1_TILES "tilesets/LEVEL1_TILES.png"

#define OBJ_LEVEL1_OBJECTS "objects/LEVEL1_OBJECTS.png"
#define OBJ_SPRITESHEET_GAME "objects/GAME.png"
#define OBJ_CHECKPOINT "objects/CHECKPOINT.png"
#define OBJ_SUPERCHECKPOINT "objects/SUPERCHECKPOINT.png"
#define OBJ_CRUMBLINGPEG "objects/CRUMBLINGPEG.png"
#define OBJ_EXTRALIFE "objects/EXTRALIFE.png"
#define OBJ_HANDS4 "objects/HANDS4.png"
#define OBJ_MANICAL1 "objects/MANICAL1.png"
#define OBJ_TORCH "objects/TORCH.png"
#define OBJ_TORSHSTAND "objects/TORSHSTAND.png"
#define OBJ_CRATES "objects/CRATES.png"
#define OBJ_COINS "objects/COINS.png"
#define OBJ_WARP "objects/WARP.png"
#define OBJ_VERTWARP "objects/VERTWARP.png"
#define OBJ_BOSSWARP "objects/BOSSWARP.png"
#define OBJ_DYNAMITELIT1 "objects/DYNAMITELIT1.png"
#define OBJ_DYNAMITELIT2 "objects/DYNAMITELIT2.png"

#define CHAR_OFFICER_IDLE "characters/OFFICER/OFFICER_IDLE.png"
#define CHAR_SOLDIER_IDLE "characters/SOLDIER/SOLDIER_IDLE.png"
#define CHAR_SOLDIER_GUN_ATTACK "characters/SOLDIER/SOLDIER_GUN_ATTACK.png"
#define CHAR_SOLDIER_HURT_STANCES "characters/SOLDIER/SOLDIER_HURT_STANCES.png"
#define CHAR_SOLDIER_WALK "characters/SOLDIER/SOLDIER_WALK.png"
#define CHAR_CLAW_IDLE "characters/CLAW/CLAW_IDLE.png"
#define CHAR_CLAW_CROTCH_PISTOL_ATTACK "characters/CLAW/CLAW_CROTCH_PISTOL_ATTACK.png"
#define CHAR_CLAW_CROTCH_SWORD_ATTACK "characters/CLAW/CLAW_CROTCH_SWORD_ATTACK.png"
#define CHAR_CLAW_CLIMBING "characters/CLAW/CLAW_CLIMBING.png"
#define CHAR_CLAW_FALLING "characters/CLAW/CLAW_FALLING.png"
#define CHAR_CLAW_HURT "characters/CLAW/CLAW_HURT.png"
#define CHAR_CLAW_JUMP "characters/CLAW/CLAW_JUMP.png"
#define CHAR_CLAW_MELEE_ATTACK "characters/CLAW/CLAW_MELEE_ATTACK.png"
#define CHAR_CLAW_PISTOL_ATTACK "characters/CLAW/CLAW_PISTOL_ATTACK.png"
#define CHAR_CLAW_RUN "characters/CLAW/CLAW_RUN.png"
#define CHAR_CLAW_SWORD_ATTACK "characters/CLAW/CLAW_SWORD_ATTACK.png"

#define VFX_GLITTER "vfx/GLITTER.png"
#define VFX_GLITTERGREEN "vfx/GLITTERGREEN.png"
#define VFX_GLITTERRED "vfx/GLITTERRED.png"

#define UI_DYNAMITE "ui/UI_DYNAMITE.png"
#define UI_HEALTHHEART "ui/UI_HEALTHHEART.png"
#define UI_LIVESHEAD "ui/UI_LIVESHEAD.png"
#define UI_PISTOL "ui/UI_PISTOL.png"
#define UI_POWERUPS "ui/UI_POWERUPS.png"
#define UI_STOPWATCH "ui/UI_STOPWATCH.png"
#define UI_TREASURECHEST "ui/UI_TREASURECHEST.png"

#define LEVEL_ROCA "../resources/LEVELS/LEVEL1.cscene"